### Registrar un usuario
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "username": "Idiarj",
  "password": "16012004id",
  "email": "idiar16@gmail.com",
  "firstName": "Idiar",
  "lastName": "Chacin",
  "birthDate": "Thu Dec 15 2005 20:00:00 GMT-0400",
  "gender": "Hombre",
  "description": "Hola",
  "interestedIn": "Mujer"
}

### enviar email para recuperacion
POST https://t3304wpf-3000.use2.devtunnels.ms/user/sendEmailRecovery
Content-Type: application/json

{
  "email": "idiar16@gmail.com"
}

### enviar email para recuperacion
POST http://localhost:3000/user/sendEmailRecovery
Content-Type: application/json

{
  "email": "idiar16@gmail.com"
}

### ver pregunta de seguridad
GET http://localhost:3000/user/getSecurityQuestion